# Generated by Django 2.0 on 2020-09-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200905_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
