# Generated by Django 2.0 on 2020-09-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200925_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Item'),
        ),
    ]
