# Generated by Django 2.0 on 2020-09-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200926_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='post',
            new_name='item',
        ),
    ]
