# Generated by Django 2.0 on 2020-09-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200926_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='slider_image',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='slider_image_1',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='slider_image_2',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
    ]
