# Generated by Django 2.0 on 2020-09-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200926_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
