# Generated by Django 2.0 on 2020-09-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_settings_about_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about_image',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
        migrations.AddField(
            model_name='settings',
            name='about_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
