# Generated by Django 2.0 on 2020-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200926_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
