# Generated by Django 2.0 on 2020-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200926_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
