# Generated by Django 2.0 on 2020-10-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
