# Generated by Django 2.0 on 2020-10-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
    ]
