# Generated by Django 2.0 on 2020-10-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201012_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brendcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brendcategory', to='core.BrendCategory'),
        ),
    ]
