# Generated by Django 2.0 on 2020-10-18 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_category_brendcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brendcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='brendcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BrendCategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
