# Generated by Django 2.0 on 2020-10-20 10:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201018_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='brendcategory',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
            preserve_default=False,
        ),
    ]
