# Generated by Django 2.0 on 2020-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_brendcategory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brendcategory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
