# Generated by Django 2.0 on 2020-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201020_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brendcategory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
