# Generated by Django 2.0 on 2020-10-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201021_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brendcategory',
            name='quantity',
        ),
    ]
