# Generated by Django 2.0 on 2020-10-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_brendcategory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='other_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
