# Generated by Django 2.0 on 2020-10-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201024_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
