# Generated by Django 2.0 on 2020-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_item_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='other_title_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='other_title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='specification_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='specification_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
