# Generated by Django 2.0 on 2020-11-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
