# Generated by Django 2.0 on 2020-11-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_settings_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='order_number_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='order_number_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
