# Generated by Django 2.0 on 2020-11-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201123_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='order_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='order_content_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='order_content_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
